import numpy as np
from sklearn.linear_model import LinearRegression


class Forecaster:
    """Simple linear-regression-based price forecaster."""

    def forecast(self, symbol: str, prices: list[float], horizon: int = 30) -> dict:
        if len(prices) < 10:
            return {"symbol": symbol, "error": "Insufficient historical data"}

        y = np.array(prices)
        x = np.arange(len(y)).reshape(-1, 1)

        model = LinearRegression()
        model.fit(x, y)

        future_x = np.arange(len(y), len(y) + horizon).reshape(-1, 1)
        predicted = model.predict(future_x).tolist()

        current = prices[-1]
        forecast_end = predicted[-1]
        expected_return = (forecast_end - current) / current * 100

        return {
            "symbol": symbol,
            "current_price": round(current, 2),
            "forecast_horizon_days": horizon,
            "predicted_prices": [round(p, 2) for p in predicted],
            "expected_return_pct": round(expected_return, 2),
            "confidence": "low",
            "disclaimer": (
                "This forecast is generated by a simple linear model for demonstration "
                "purposes only and should not be used for investment decisions."
            ),
        }
